name: Bug report
description: Report bugs or issues.
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! The more info you provide, the faster we can help you. Before you proceed, please confirm that there isn't [already an issue](https://github.com/ponder-sh/ponder/issues) for this bug.

  - type: input
    attributes:
      label: Version
      description: What version of `ponder` or `@ponder/core` are you using?
      placeholder: x.y.z (do not write `latest`)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Current behavior
      description: A concise description of what you're experiencing.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Expected behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Steps or code snippets to reproduce the behavior (`ponder.config.ts`, `ponder.schema.ts`, indexing functions, ABIs, etc).
    validations:
      required: false

  - type: input
    attributes:
      label: Link to repository
      description: The public repository containing your Ponder app.
      placeholder: https://github.com/...
    validations:
      required: false

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Logs? Screenshots? Anything that might help us understand or reproduce the issue. Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
